# Numpy

In [1]:
# IMPORTS
import numpy as np
import time

## 1. Creación de Arrays

- 1.1 np.array()

- 1.2 Array 1D, 2D, 3D

- 1.3 Array's Utiles

- 1.4 Reshape()

## 1.1 Cómo crear una array en numPy

In [3]:
# Lista en python
lista_py = [1,2,3,4,5]
print("Lista en Python:", lista_py)
print("Tipo de datos:", type(lista_py))

# Lista en numpy
array_numpy = np.array([1,2,3,4,5])
print("Lista en Numpy:", array_numpy)
print("Tipo de datos:", type(array_numpy))

Lista en Python: [1, 2, 3, 4, 5]
Tipo de datos: <class 'list'>
Lista en Numpy: [1 2 3 4 5]
Tipo de datos: <class 'numpy.ndarray'>


## 1.2 Por qué ocupamos NumPy

In [2]:
lista_grande = list(range(10000000))
array_grande = np.array(lista_grande)

inicio_timer1 = time.time()
lista_cuadrado = [i**2 for i in lista_grande]
fin_timer1 = time.time() - inicio_timer1

inicio_timer2 = time.time()
array_cuadrado = array_grande**2
fin_timer2 = time.time() - inicio_timer2

print("Tiempo de ejecución lista:", fin_timer1)
print("Tiempo de ejecución array:", fin_timer2)

Tiempo de ejecución lista: 2.225424289703369
Tiempo de ejecución array: 0.11319541931152344


## 1.3 Creando Arrays más grandes

In [8]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray 2D:")
print(array_2d)
print("Forma del array 2D:", array_2d.shape)
print("Número de dimensiones:", array_2d.ndim)

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nArray 3D:")
print(array_3d)
print("Forma del array 3D:", array_3d.shape)
print("Número de dimensiones:", array_3d.ndim)



Array 2D:
[[1 2 3]
 [4 5 6]]
Forma del array 2D: (2, 3)
Número de dimensiones: 2

Array 3D:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Forma del array 3D: (2, 2, 2)
Número de dimensiones: 3


## 1.4 Funciones útiles para crear arrays

In [10]:
# ARRANGE
array_arange_simple = np.arange(10)
print(array_arange_simple, "\n")

array_arange_steps = np.arange(0, 10, 2)
print(array_arange_steps, "\n")

[0 1 2 3 4 5 6 7 8 9] 

[0 2 4 6 8] 



In [18]:
#LINSPACE
array_linspace1 = np.linspace(1, 10, 10)
print(array_linspace1, "\n")

array_linspace2 = np.linspace(0, 100, 5)
print(array_linspace2, "\n")


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 

[  0.  25.  50.  75. 100.] 



In [20]:
# ZEROS
array_zeros = np.zeros((3,3))
print(array_zeros, "\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [21]:
# ONES
array_ones = np.ones((3,3))
print(array_ones, "\n")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



In [23]:
# FULL
array_full = np.full((3,3), np.pi)
print(array_full, "\n")

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]] 



In [24]:
# IDENTIDAD
array_identidad = np.eye(3)
print(array_identidad, "\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [43]:
# RESHAPE
array_original = np.arange(9)
print("Array original: \n", array_original, "\n")

array_reshape = array_original.reshape(3,3)
print("Array reshape: \n", array_reshape, "\n")

array_original2 = np.arange(9).reshape(3,3)
print("Array original 2: \n", array_original2, "\n")

array_reshape2 = array_original2.reshape(9,1)
print("Array reshape2: \n", array_reshape2, "\n")


Array original: 
 [0 1 2 3 4 5 6 7 8] 

Array reshape: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Array original 2: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Array reshape2: 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 



# 2. Propiedades e Indexación

## 2.1 Propiedades

In [64]:
Array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array Base: \n",Array , "\n")

# SHAPE
print("Forma del array: ", Array.shape, "\n")

# SIZE
print("Cantidad de elementos: ", Array.size, "\n")

# DIMESNIONES
print("Número de dimesniones: ", Array.ndim, "\n")

# TIPO DE DATOS (Prueben cambiar un unico elemeto a float)
print("Tipo de datos en el array: ", Array.dtype, "\n")

# TAMAÑO EN MEMORI (8 bits = 1 Byte)
print("Tamaño en bytes: ", Array.nbytes)

Array Base: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Forma del array:  (3, 3) 

Cantidad de elementos:  9 

Número de dimesniones:  2 

Tipo de datos en el array:  int64 

Tamaño en bytes:  72


## 2.2 Conversión de tipos de datos

In [70]:
array_int = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array original (int64):")
print(array_int)
print("Tipo de datos:", array_int.dtype)
print("Tamaño total en bytes:", array_int.nbytes, "bytes\n")

array_float = array_int.astype(np.float64)
print("Array convertido a float64:")
print(array_float)
print("Tamaño total en bytes:", array_float.nbytes, "bytes\n")

array_int8 = array_int.astype(np.int8)
print("Array convertido a int8:")
print(array_int8)
print("Tamaño total en bytes:", array_int8.nbytes, "bytes\n")

Array original (int64):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Tipo de datos: int64
Tamaño total en bytes: 72 bytes

Array convertido a float64:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Tamaño total en bytes: 72 bytes

Array convertido a int8:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Tamaño total en bytes: 9 bytes



## 2.3 Indexación y Slicing

In [90]:
array_ejemplo = np.array([[11, 12, 13, 14, 15],
                          [16, 17, 18, 19, 20],
                          [21, 22, 23, 24, 25],
                          [26, 27, 28, 29, 30],
                          [31, 32, 33, 34, 35]])
print("Matriz de ejemplo:")
print(array_ejemplo)

# INDEXACIÓN BÁSICA
print("\nElemento en la posición (0,0):", array_ejemplo[0, 0])
print("\nElemento en la posición (2,2):", array_ejemplo[2, 2], "\n")

# SLICING
print("Entender la notación ':' \n")
print(array_ejemplo[:,:], "\n")

print("Submatriz con las dos primeras filas:")
print(array_ejemplo[:2, :], "\n")

print("Elementos de la primera fila del indice 1 al 2")
print(array_ejemplo[0,1:3],"\n")

print("Todas las filas, con saltos en las columnas")
print(array_ejemplo[:, ::2])

Matriz de ejemplo:
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]

Elemento en la posición (0,0): 11

Elemento en la posición (2,2): 23 

Entender la notación ':' 

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] 

Submatriz con las dos primeras filas:
[[11 12 13 14 15]
 [16 17 18 19 20]] 

Elementos de la primera fila del indice 1 al 2
[12 13] 

Todas las filas, con saltos en las columnas
[[11 13 15]
 [16 18 20]
 [21 23 25]
 [26 28 30]
 [31 33 35]]
