# **Ayudantía 10 - Ejercicios C2**
## Etienne Rojas

Ante cualquier duda o posible corrección, por favor mandar un correo a `etienne.rojas@sansano.usm.cl` 


---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# **Ejercicio 2.4 Ajedrez**

## Función Auxiliar

In [ ]:
def ChessMatrixTransform(n, Dn):
    '''
    Transforma la matriz compacta D^{(n)} [2N X N+1] en la matriz C^{(n)} [2N X 2N]
    La matriz C^{(n)} es una matriz de ajedrez que contiene los elementos de D^{(n)}
    En posiciones espaciadas por elementos nulos a excepcion de las ultimas 2 columnas
    que son iguales a las ultimas 2 columnas de D^{(n)}.

    Args:
        n (int): Índice de la matriz C^{(n)} y D^{(n)}.
        Dn (ndarray): Matriz compacta de tamaño [2N X N+1] que almacena los no nulos de C^{(n)}.
    
    Returns:
        C (ndarray): Matriz de ajedrez de tamaño [2N X 2N] que contiene los elementos de D^{(n)} en forma de ajedrez.
    '''
    
    # ACA VA SU CÓDIGO



    # ----------------

    return C

n = 3
Dn = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 1, 2],
    [3, 4, 5, 6],
    [7, 8, 9, 10],
    [1, 2, 3, 4],
])
C = ChessMatrixTransform(n, Dn)
print(C)

In [ ]:
def OneStepJacobi(n, Dn, b, x0):
    '''
    Realiza una iteración del método de Jacobi para la matriz C^{(n)} almacenada en Dn.
    
    Args:
        n (int): Índice de la matriz C^{(n)} y D^{(n)}.
        Dn (ndarray): Matriz compacta de tamaño 2n x (n+1) que almacena los no nulos de C^{(n)}.
        b (ndarray): Vector del lado derecho de tamaño 2n.
        x0 (ndarray): Vector inicial de tamaño 2n.
    
    Returns:
        x1 (ndarray): Nuevo vector después de una iteración de Jacobi.
    '''
    # ACA VA SU CÓDIGO



    # ----------------
    
    return x1

## **Testear el Código**

In [ ]:
n = 2
Dn = np.array([
    [50.0, 1.0, 1.0],
    [50.0, 1.0, 1.0],
    [1.0, 50.0, 1.0],
    [1.0, 1.0, 50.0],
])

C = ChessMatrixTransform(n, Dn)

x_real = np.array([1.0, 2.0, 3.0, 4.0])

b = C @ x_real

x0 = np.array([10.0, 10.0, 10.0, 10.0])


x = x0.copy()
for i in range(7):
    x = OneStepJacobi(n, Dn, b, x)
    print(f"Iteración {i+1}: {x}")


print("\nSolución real:", x_real)
print("Aproximación final:", x)
print("Error absoluto:", np.abs(x - x_real))

---

## **Ejercicio 2.12 ¿Es o no es tridiagonal?**

#### **Parámetros Generales**

In [2]:
a = 10
b = -4
c = 1/2
n = 3

In [ ]:
def build_matrix_A(a,b,c,n):
    """
    Construye la matriz A de un sistema NO tridiagonal de tamaño n x n.
    
    Input:
        a (float): Valor en la diagonal secundario
        b (float): Valor en la diagonal secundaria superior.
        c (float): Valor en la diagonal secundaria inferior.
        n (int): Tamaño de la matriz.
    
    Output:
        A (ndarray): Matriz NO tridiagonal de tamaño n x n.
    """
    # ACA VA SU CÓDIGO
    A = np.zeros((n, n))

    np.fill_diagonal(A[1:, :-1], b)
    np.fill_diagonal(A, a)
    np.fill_diagonal(A[:-1, 1:], c)
    
    A_invertida = A[::-1]
    A = A_invertida
    return A
    # ----------------
    return A

A = build_matrix_A(a, b, c, n)
print("Matriz A:")
print(A)

Matriz A:
[[ 0.  -4.  10. ]
 [-4.  10.   0.5]
 [10.   0.5  0. ]]


In [8]:
def build_vector_b(n):
    """
    Construye el vector b de la ecuacion Ax=b
    Donde los elementos van desde son = 1/i hasta 1/n
    con i = 1, 2, ..., n.
    
    Input:
        n (int): Tamaño del vector.
    
    Output:
        b (ndarray): Vector de tamaño n con los elementos 1/i.
    """
    # ACA VA SU CÓDIGO
    b = 1 / np.arange(1, n + 1)
    return b

    # ----------------

vector_b = build_vector_b(n)
print("Vector b:")
print(vector_b)

Vector b:
[1.         0.5        0.33333333]


In [20]:
def solve_system(A, vector_b,n):
    """
    Resuelve el sistema Ax = b utilizando el método desarrollado.
    En la parte teórica del problema.
    Input:
        A (ndarray): Matriz del sistema.
        b (ndarray): Vector del lado derecho.
        n (int): tamaño del vector b y de la matriz A.
    
    Output:
        x (ndarray): Solución del sistema.
    """

   # ACA VA SU CÓDIGO
    
    A = A.copy()
    A = A[::-1]
    vector_b = vector_b.copy()
    vector_b = vector_b[::-1]

    A_diag_inv = np.diag(1 / np.diag(A))
    A_low = np.tril(A, k=-1)
    A_up = np.triu(A, k=1)
    
    num_iterations = 5

    xi = np.ones(n)
    for _ in range(num_iterations): 
        xi = A_diag_inv @ (vector_b - (A_low + A_up) @ xi)
        Ax = A @ xi
        error = np.linalg.norm(Ax-b)
        print("x", xi)
        print("error:", error)

    x= xi    
    return x


    # ---------------- 

In [21]:

print("Resolviendo el sistema Ax = b...")
print(A,"x=", vector_b)

print("Solución del sistema:")
x_solution = solve_system(A, vector_b, n)
print("x:",x_solution)

print("Comprobación Ax = b:")
Ax = A @ x_solution
print("Ax:", Ax)
print("b:", vector_b)

Resolviendo el sistema Ax = b...
[[ 0.  -4.  10. ]
 [-4.  10.   0.5]
 [10.   0.5  0. ]] x= [1.         0.5        0.33333333]
Solución del sistema:
x [-0.01666667  0.4         0.5       ]
error: 11.840385222712234
x [0.01333333 0.01833333 0.26      ]
error: 8.826397001482416
x [0.03241667 0.04233333 0.10733333]
error: 7.863233742480818
x [0.03121667 0.0576     0.11693333]
error: 7.973302090866884
x [0.03045333 0.05664    0.12304   ]
error: 8.007311037118239
x: [0.03045333 0.05664    0.12304   ]
Comprobación Ax = b:
Ax: [1.00384    0.50610667 0.33285333]
b: [1.         0.5        0.33333333]
