# **Ayudantía 4 - Sistemas de Ecuaciones Lineales**
## Etienne Rojas

Ante cualquier duda o posible corrección, por favor mandar un correo a `etienne.rojas@sansano.usm.cl` 

---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# **Repaso Materia**


## **Recordando la Regla de Cramer**

$$
x = \frac{
\left| \begin{array}{cc}
c_1 & b_1 \\
c_2 & b_2
\end{array} \right|
}{
\left| \begin{array}{cc}
a_1 & b_1 \\
a_2 & b_2
\end{array} \right|
},
$$

$$
x = \frac{
\left| \begin{array}{cc}
a_1 & c_1 \\
a_2 & c_2
\end{array} \right|
}{
\left| \begin{array}{cc}
a_1 & b_1 \\
a_2 & b_2
\end{array} \right|
}
$$

- Es fácil de etender y bastante directo.
- El problema es que la naturaleza del operador **Determinante** es **RECURSIVA**.
- En el peor caso calcular el determinande de una matriz $(n \times n)$ es $\mathcal{O}(n!)$.

---

## **Caso Matriz Triangular**

Si partimos desde:

$$
\begin{bmatrix}
a & b \\
0 & c
\end{bmatrix}
\begin{bmatrix}
x \\
y
\end{bmatrix}
=
\begin{bmatrix}
d \\
e
\end{bmatrix}
$$

Si lo ponenes como un listado de ecuaciones:


$$
\begin{aligned}
ax + by &= d, \\
0x + cy &= e.
\end{aligned}
$$

Es fácil notar que la solucion es:

$$
\begin{aligned}
    y &= \frac{e}{c} \\
    x &= \frac{d-by}{a}
\end{aligned}
$$


Dada la triangularidad superior de la matriz inicial, es sencillo resolver el sistema. De aquí es donde nace la necesidad o la intención de llevar un sistema inicial $A$ a una equivalente $A'$ donde la matriz sea triangular superior.

---


## **Eliminación Gaussiana**
Vamos a recordar rapidamente la Eliminación Gaussiana aplicandola sobre este sistema:

$$
\begin{bmatrix}
2 & 3 & 4 \\
1 & 2 & 3 \\
3 & -4 & 0
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
6 \\
4 \\
10
\end{bmatrix}
$$

- El mayor problema de la eliminación Gaussiana es que necesita $\sim \frac{2}{3}n^3$ operaciones elementales.

---

# **Backward Substitution**

Acabamos de aplicar **Backward Substitution** para resolver una matriz triangular resultante de la **Eliminación Gaussiana**. Ahora vamos a formalizar este procedimiento en un caso más general.

$$
\begin{bmatrix}
u_{11} & u_{12} & u_{13} & u_{14} & u_{15} \\
  0    & u_{22} & u_{23} & u_{24} & u_{25} \\
  0    &   0    & u_{33} & u_{34} & u_{35} \\
  0    &   0    &   0    & u_{44} & u_{45} \\
  0    &   0    &   0    &    0   & u_{55} \\

\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
x_5 \\
\end{bmatrix}
=
\begin{bmatrix}
b_1 \\
b_2 \\
b_3 \\
b_4 \\
b_5 
\end{bmatrix}
$$

- Hagamos todos juntos el Backward Substitution.


$$
x_i = \frac{b_i- \sum_{j=i+1}^n u_{i,j}x_j}{u_{i,i}}
$$

- El algoritmo requiere $n^2$ operaciones

---

# **Factorización LU**
**La factorización LU** consiste en descomponer una matriz cuadrada \( A \) como el producto de dos matrices:

$$
 A = LU
$$
donde:
- $L$ es una matriz triangular inferior,
- $U$ es una matriz triangular superior.

Esta factorización esencialmente **almacena los pasos de la eliminación gaussiana** en $L$ y $U$, permitiendo resolver sistemas lineales de forma más eficiente.

Apliquemos la factorización a la siguiente matriz:

$$
A = \begin{bmatrix}
2 & 1 & 1 \\
4 & 3 & 3 \\
8 & 7 & 9 \\
\end{bmatrix}
$$




In [2]:
# Usamos python para confimar que el resultado es correcto
A = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]])


L = np.array([[1, 0, 0],
              [2, 1, 0],
              [4, 3, 1]])

U = np.array([[2, 1, 1],
              [0, 1, 1],
              [0, 0, 2]])

print("Matriz original A: \n", A, "\n")
print("Matriz L: \n", L, "\n")
print("Matriz U: \n", U, "\n")
print("Multiplicando L y U:")
print(L @ U, "\n")

Matriz original A: 
 [[2 1 1]
 [4 3 3]
 [8 7 9]] 

Matriz L: 
 [[1 0 0]
 [2 1 0]
 [4 3 1]] 

Matriz U: 
 [[2 1 1]
 [0 1 1]
 [0 0 2]] 

Multiplicando L y U:
[[2 1 1]
 [4 3 3]
 [8 7 9]] 



## **LA FACTORIZACIÓN FUNCIONA, PERO ¿FUNCIONARA SIEMPRE?**

Calcule la factorización LU de la siguiente matriz $A$:

$$
A= 
\begin{bmatrix}
2 & 3 & 4 \\
1 & 2 & 3 \\
3 & -4 & 0
\end{bmatrix}
$$

In [3]:
# Usamos python para confimar que el resultado es correcto
A = np.array([[2, 3, 4],
              [1, 2, 3],
              [3, -4, 0]])


L = np.array([[1, 0, 0],
              [2, 1, 0],
              [3, 10, 1]])

U = np.array([[1, 2, 3],
              [0, -1, -2],
              [0, 0, 11]])

print("Matriz original A: \n", A, "\n")
print("Matriz L: \n", L, "\n")
print("Matriz U: \n", U, "\n")
print("Multiplicando L y U:")
print(L @ U, "\n")

Matriz original A: 
 [[ 2  3  4]
 [ 1  2  3]
 [ 3 -4  0]] 

Matriz L: 
 [[ 1  0  0]
 [ 2  1  0]
 [ 3 10  1]] 

Matriz U: 
 [[ 1  2  3]
 [ 0 -1 -2]
 [ 0  0 11]] 

Multiplicando L y U:
[[ 1  2  3]
 [ 2  3  4]
 [ 3 -4  0]] 



# **Factorización $PA = LU$**
Como acabamos de ver, con la matriz anterior, si no hacemos el cambio de filas el sistema no se puede resolver, pero si hacemos la permutación la factorización LU no es capaz de almacenar la permutacion de filas, por lo cual $A \neq LU$ más bien, estamos haciendo $A' = LU$ donde $A'$ es la matriz $A$ luego de realizar la permutación de filas.

## **¿Cómo definir una matriz de permutaciones?**
En el ejemplo anterior realizamos una permutación entre la fila 1 y 2 de una matriz $3 \times 3$. ¿cómo podemos crear una matriz que al multiplicarla por $A$ tenga ese efecto?

In [7]:
P = np.array([
              [0, 1, 0],
              [1, 0, 0],
              [0, 0, 1]
              ])

A = np.array([[1, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])

print("Matriz original A: \n", A, "\n")
print("Matriz de permutación P: \n", P, "\n")
print("Multiplicando P y A:")
print(P @ A, "\n")

Matriz original A: 
 [[1 1 1]
 [2 2 2]
 [3 3 3]] 

Matriz de permutación P: 
 [[0 1 0]
 [1 0 0]
 [0 0 1]] 

Multiplicando P y A:
[[2 2 2]
 [1 1 1]
 [3 3 3]] 



---

# **EJERCICIO 1**
Resuelva el siguiente sistema de ecuaciones utilizando la factorización $PA = LU$

$$
\begin{aligned}
0x + 2y + z &= 4 \\
3x + 8y + 7z &= 20 \\
2x + 6y + 4z &= 13 \\
\end{aligned}
$$

---

# **Pauta**


## **Pasamos a forma matricial**
$$

\begin{bmatrix}
0 & 2 & 1 \\
3 & 8 & 7 \\
2 & 6 & 4 \\
\end{bmatrix}

\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}

=
\begin{bmatrix}
4 \\
20 \\
13 \\
\end{bmatrix}

$$

## **Necesitamos Cambiar el Pivote**
$$
P =
\begin{bmatrix}
0 & 1 & 0 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$

$$
PA =
\begin{bmatrix}
3 & 8 & 7 \\
0 & 2 & 1 \\
2 & 6 & 4 \\
\end{bmatrix}
$$

## **El Sistema post permutaciones**
$$
PA \vec{x} = P \vec{b}
$$

$$
\begin{bmatrix}
3 & 8 & 7 \\
0 & 2 & 1 \\
2 & 6 & 4 \\
\end{bmatrix} 

\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}
= 

\begin{bmatrix}
20 \\
4 \\
13 \\
\end{bmatrix}
$$

## **Aplicamos LU**



$$
LU \vec{x} = P \vec{b}
$$

$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
2/3 & 1/3 & 1 \\
\end{bmatrix} 

\begin{bmatrix}
3 & 8 & 7 \\
0 & 2 & 1 \\
0 & 0 & -1 \\
\end{bmatrix} 

\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
\end{bmatrix}=

\begin{bmatrix}
20 \\
4 \\
13 \\
\end{bmatrix}
$$

In [16]:
# Usamos python para confimar que factorizamos bien
PA = np.array([[3, 8, 7],
               [0, 2, 1],
               [2, 6, 4]])

L = np.array([[1, 0, 0],
              [0, 1, 0],
              [2/3, 1/3, 1]])

U = np.array([[3, 8, 7],
              [0, 2, 1],
              [0, 0, -1]])


print("Matriz original PA: \n", PA, "\n")
print("Matriz L: \n", L, "\n")
print("Matriz U: \n", U, "\n")
print("Multiplicando L y U:")
print(L @ U, "\n")

Matriz original PA: 
 [[3 8 7]
 [0 2 1]
 [2 6 4]] 

Matriz L: 
 [[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.66666667 0.33333333 1.        ]] 

Matriz U: 
 [[ 3  8  7]
 [ 0  2  1]
 [ 0  0 -1]] 

Multiplicando L y U:
[[3. 8. 7.]
 [0. 2. 1.]
 [2. 6. 4.]] 



# **Aplicamos el trucazo**

$$
U \vec{x} = \vec{z}
$$
Entonces llegamos a 

$$
L \vec{z} = P\vec{b}
$$

$$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
2/3 & 1/3 & 1 \\
\end{bmatrix} 

\begin{bmatrix}
z_1 \\
z_2 \\
z_3 \\
\end{bmatrix}=

\begin{bmatrix}
20 \\
4 \\
13 \\
\end{bmatrix}
$$

## **Fordward Substitution**

$$
z_1 = 20
$$

$$
z_2 = \frac{-28}{3}
$$

$$
z_3 = \frac{173}{9}
$$