# **Ayudantía 5 - PA LU**
## Etienne Rojas

Ante cualquier duda o posible corrección, por favor mandar un correo a `etienne.rojas@sansano.usm.cl` 

---

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# **Ejercicio 1**

Considera la matriz $A \in \mathbb{R}^{n \times n}$ definida como:

$$
A_{ij} = \begin{cases}
1, \quad i=j    \\
-1, \quad i>j   \\
1, \quad j=n    \\
0, \quad en\;otro\;caso
\end{cases}
$$


**Parte (a)**: Para $n = 4$, encuentra matrices $P$, $L$ y $U$ tal que:

$$
PA = LU
$$


**Parte (b)**: Generaliza la factorización LU para una matriz $A_n$ con la estructura dada para tamaño arbitrario $n$. Describe las formas generales de $L$ y $U$ y demuestre por inducción que su factorización es correcta.



---

# **Pauta Ejercicio 1**

## **Part3 a**

La matriz dada es:

$$
A = 
\begin{bmatrix}
1 & 0 & 0 & 1 \\
-1 & 1 & 0 & 1 \\
-1 & -1 & 1 & 1 \\
-1 & -1 & -1 & 1
\end{bmatrix}
$$

**Paso 1: Primer pivote (columna 1)**

Multiplicadores:
- $m_{21} = -1$, $m_{31} = -1$, $m_{41} = -1$

Actualizamos:
- R2 ← R2 + 1×R1 ⇒ $[0, 1, 0, 2]$
- R3 ← R3 + 1×R1 ⇒ $[0, -1, 1, 2]$
- R4 ← R4 + 1×R1 ⇒ $[0, -1, -1, 2]$


**Paso 2: Segundo pivote (columna 2)**


Multiplicadores:
- $m_{32} = -1$, $m_{42} = -1$

Actualizamos:
- F3 ← F3 + 1×F2 ⇒ $[0, 0, 1, 4]$
- F4 ← F4 + 1×F2 ⇒ $[0, 0, -1, 4]$


**Paso 3: Tercer pivote (columna 3)**

Multiplicador:
- $m_{43} = -1$

Actualizamos:
- F4 ← F4 + 1×F3 ⇒ $[0, 0, 0, 8]$


**Matrices resultantes**

$$
L = 
\begin{bmatrix}
1 & 0 & 0 & 0 \\
-1 & 1 & 0 & 0 \\
-1 & -1 & 1 & 0 \\
-1 & -1 & -1 & 1
\end{bmatrix},
\quad
U = 
\begin{bmatrix}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 2 \\
0 & 0 & 1 & 4 \\
0 & 0 & 0 & 8
\end{bmatrix}
$$

Como no fue necesario pivotear:

$$
P = I
\quad \Rightarrow \quad
\boxed{A = LU}
$$

Puedes verificar que $LU = A$ haciendo la multiplicación.


In [2]:
A4 = np.array([[ 1, 0, 0, 1], 
               [-1, 1, 0, 1], 
               [-1,-1, 1, 1], 
               [-1,-1,-1, 1]])

L4 = np.array([[ 1, 0, 0, 0],
               [-1, 1, 0, 0], 
               [-1,-1, 1, 0], 
               [-1,-1,-1, 1]])

U4 = np.array([[ 1, 0, 0, 1],
               [ 0, 1, 0, 2], 
               [ 0, 0, 1, 4], 
               [ 0, 0, 0, 8]])

print("A4 = \n", A4)
print("L4@U4 = \n", L4@U4)

A4 = 
 [[ 1  0  0  1]
 [-1  1  0  1]
 [-1 -1  1  1]
 [-1 -1 -1  1]]
L4@U4 = 
 [[ 1  0  0  1]
 [-1  1  0  1]
 [-1 -1  1  1]
 [-1 -1 -1  1]]


---

## **Parte b**


Lo hacemos en la pizarra :p

---

## **Ejercicio 2**


Complete la siguiente lista de funciones donde la matriz A es la matriz del ejercicio 1.

In [20]:
# PARAMETROS GENEREALES
# ----------------------------------------
N = 5 # Tamaño de las matrices
seed= 42

In [40]:
# IMPORTANTE CONOCER ESTA FUNCION

np.ones((N,N))
A = np.arange(1, 17).reshape(4, 4)
print("Matriz original A:\n", A)

# Obtener la parte triangular inferior
L = np.tril(A)
print("\nParte triangular inferior de A (np.tril):\n", L)

Matriz original A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Parte triangular inferior de A (np.tril):
 [[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]


In [ ]:
def generate_random_b_estudiantes(N, seed =42):
    """
    Genera un vector b aleatorio de tamaño N con valores enterose entre 0 y 9.
    Tiene que utilizar la semilla seed=42 para que los resultados sean reproducibles.
    """
    # SU CODIGO VA ACA
    #-----------------


    #-----------------
    return b
    
# print("b = \n", generate_random_b_estudiantes(N,seed))

In [34]:
def create_matrix_A_estudiantes(N):
    """
    Construye la matriz A de tamaño n x n:
    - 1 en la diagonal
    - -1 debajo de la diagonal (excepto en la última columna)
    - 1 en toda la última columna
    """
    # SU CODIGO VA ACA
    #-----------------



    #-----------------
    return A

#A_N = create_matrix_A_estudiantes(N)
#print("A_N = \n", A_N)

In [41]:
def LU_factorization_estudiantes(N):
    """
    Factoriza la matriz A en L y U.
    L es una matriz triangular inferior con 1s en la diagonal.
    U es una matriz triangular superior.
    """
    # SU CODIGO VA ACA
    #-----------------


    #------------------
    return L,U

# L_N, U_N = LU_factorization_estudiantes(N)
# print("L_N = \n", L_N)
# print("U_N = \n", U_N)

In [44]:
def backward_substitution_estudiantes(U, c):
    """
    Resuelve el sistema Ux = c por sustitución hacia atrás.
    U debe ser una matriz triangular superior.
    """
    # SU CODIGO VA ACA
    #-----------------



    #-----------------
    return x


In [45]:
def forward_substitution_estudiantes(L, b):
    """
    Resuelve el sistema Lx = b por sustitución hacia adelante.
    L debe ser una matriz triangular inferior.
    """
    # SU CODIGO VA ACA
    #-----------------

    #-----------------
    return x

In [ ]:
A_N = create_matrix_A_estudiantes(N)
b_N = generate_random_b_estudiantes(N, seed)

print("SISTEMA DE ECUACIONES LINEALES\n")
print("A x = b")
print("A_N = \n", A_N)
print("b_N = \n", b_N)
print("\n")

L_N, U_N = LU_factorization_estudiantes(N)
print("FACTORIZACION LU de A_N\n")
print("L_N = \n", L_N)
print("U_N = \n", U_N)
print("\n")

print("RESOLVEMOS EL SISTEMA USANDO LA LU\n")
c_N = forward_substitution_estudiantes(L_N, b_N)
x_N = backward_substitution_estudiantes(U_N, c_N)

print("COMPROBAMOS QUE LA SOLUCION ES CORRECTA\n")
print("A_N @ x_N = \n", A_N @ x_N)
print("b_N = \n", b_N)

---

# **PAUTA EJERCICIO 2**

In [47]:
def generate_random_b(N, seed =42):
    """
    Genera un vector b aleatorio de tamaño N con valores enterose entre 0 y 9.
    Tiene que utilizar la semilla seed=42 para que los resultados sean reproducibles.
    """
    np.random.seed(seed)
    b = np.random.randint(0, 10, size=(N, 1))
    return b
    
print("b = \n", generate_random_b(N,seed))

b = 
 [[6]
 [3]
 [7]
 [4]
 [6]]


In [48]:
def create_matrix_A(N):
    """
    Construye la matriz A de tamaño n x n:
    - 1 en la diagonal
    - -1 debajo de la diagonal (excepto en la última columna)
    - 1 en toda la última columna
    """
    A = np.zeros((N, N))

    np.fill_diagonal(A, 1)

    filas, columnas = np.tril_indices(N, k=-1)
    A[filas, columnas] = -1

    A[:, -1] = 1

    return A

A_N = create_matrix_A(N)
print("A_N = \n", A_N)

A_N = 
 [[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]


In [49]:
def LU_factorization(N):
    """
    Factoriza la matriz A en L y U.
    L es una matriz triangular inferior con 1s en la diagonal.
    U es una matriz triangular superior.
    """
    L = np.tril(-np.ones((N, N)), k=-1) + np.eye(N)
    
    U = np.zeros((N, N))
    np.fill_diagonal(U, 1)
    U[:, -1] = 2 ** np.arange(N)
    return L,U

L_N, U_N = LU_factorization(N)
print("L_N = \n", L_N)
print("U_N = \n", U_N)

L_N = 
 [[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [-1. -1.  1.  0.  0.]
 [-1. -1. -1.  1.  0.]
 [-1. -1. -1. -1.  1.]]
U_N = 
 [[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  4.]
 [ 0.  0.  0.  1.  8.]
 [ 0.  0.  0.  0. 16.]]


In [50]:
def backward_substitution(U, c):
    """
    Resuelve el sistema Ux = c por sustitución hacia atrás.
    U debe ser una matriz triangular superior.
    """
    n = U.shape[0]
    x = np.zeros(n)

    for i in reversed(range(n)):
        if U[i, i] == 0:
            raise ValueError(f"Pivote cero en U[{i},{i}]; no se puede resolver.")
        
        suma = np.dot(U[i, i+1:], x[i+1:])
        x[i] = (c[i] - suma) / U[i, i]

    return x


In [51]:
def forward_substitution(L, b):
    """
    Resuelve el sistema Lx = b por sustitución hacia adelante.
    L debe ser una matriz triangular inferior.
    """
    n = L.shape[0]
    x = np.zeros(n)

    for i in range(n):
        suma = np.dot(L[i, :i], x[:i])
        x[i] = (b[i] - suma) / L[i, i]

    return x

In [52]:
def forward_substitution(L, b):
    """
    Resuelve el sistema Lc = b por sustitución hacia adelante.
    L debe ser triangular inferior con 1s en la diagonal.
    """
    n = L.shape[0]
    c = np.zeros(n)

    for i in range(n):
        suma = np.dot(L[i, :i], c[:i])
        c[i] = b[i] - suma

    return c


In [53]:
A_N = create_matrix_A(N)
b_N = generate_random_b(N, seed)

print("SISTEMA DE ECUACIONES LINEALES\n")
print("A x = b")
print("A_N = \n", A_N)
print("b_N = \n", b_N)
print("\n")

L_N, U_N = LU_factorization(N)
print("FACTORIZACION LU de A_N\n")
print("L_N = \n", L_N)
print("U_N = \n", U_N)
print("\n")

print("RESOLVEMOS EL SISTEMA USANDO LA LU\n")
c_N = forward_substitution(L_N, b_N)
x_N = backward_substitution(U_N, c_N)

print("COMPROBAMOS QUE LA SOLUCION ES CORRECTA\n")
print("A_N @ x_N = \n", A_N @ x_N)
print("b_N = \n", b_N)

SISTEMA DE ECUACIONES LINEALES

A x = b
A_N = 
 [[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]
b_N = 
 [[6]
 [3]
 [7]
 [4]
 [6]]


FACTORIZACION LU de A_N

L_N = 
 [[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [-1. -1.  1.  0.  0.]
 [-1. -1. -1.  1.  0.]
 [-1. -1. -1. -1.  1.]]
U_N = 
 [[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  4.]
 [ 0.  0.  0.  1.  8.]
 [ 0.  0.  0.  0. 16.]]


RESOLVEMOS EL SISTEMA USANDO LA LU

COMPROBAMOS QUE LA SOLUCION ES CORRECTA

A_N @ x_N = 
 [6. 3. 7. 4. 6.]
b_N = 
 [[6]
 [3]
 [7]
 [4]
 [6]]


C:\Users\56940\AppData\Local\Temp\ipykernel_14776\2519720270.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  c[i] = b[i] - suma
